# Generated by Django 5.1.1 on 2024-10-26 15:06

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=0, max_digits=12)),
                ('number', models.PositiveIntegerField(default=0)),
                ('image', models.ImageField(upload_to='products')),
                ('count_sold', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'product',
                'verbose_name_plural': 'products',
            },
        ),
    ]
