# Generated by Django 5.1.1 on 2024-11-04 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_productspecification'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSpecificationValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specifications', to='product.product')),
                ('specification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.productspecification')),
            ],
        ),
    ]
